version: "3.8"
volumes:
  php-fpm-socket:
  db-store:
services:
  app:
    build: ./infra/docker/php
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - ./backend:/work/backend
      - /work/backend/node_modules
      - /work/backend/vendor
      # - /work/backend/storage

  web:
    build: ./infra/docker/nginx
    ports:
      - 80:80
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - ./backend:/work/backend
      - /work/backend/node_modules
      - /work/backend/vendor
      # - /work/backend/storage

  db:
    build: ./infra/docker/mysql
    ports:
      - 3307:3307
    volumes:
      - db-store:/var/lib/mysql
